### PR TITLE
feature: Add detailed error handling for API responses

### PR DESCRIPTION
**Pull request by hummerpj**
**Title**: 
Add detailed error handling for API responses

Thanks for creating this useful tool! I ran into an issue where API errors would silently fail and insert "null" into the command prompt without any indication of what went wrong. This PR aims to improve that experience.

**Changes**:
- Catches API error responses before they turn into "null" in the prompt
- Adds structured error handling for common cases:
  - Credit balance issues
  - Rate limits
  - Authentication problems
- Uses Fish's color coding for better error visibility
- Provides users with actionable next steps

Before this change, if your API key was invalid or you ran out of credits, you'd just see "null" appear in your prompt. Now you get clear feedback about what went wrong and how to fix it.

Let me know if you'd like any adjustments to the implementation or have questions about the changes. Happy to iterate on this!

### CODE REVIEW

**Comment by hummerpj** [comment]
Here is a quick before and after, showing what it looks like

**Before**
Screenshot 2024-12-24 at 2 01 46 PM

**After**
Screenshot 2024-12-24 at 2 00 15 PM

**Review by MKSG-MugunthKumar — APPROVED** [review]

**Comment by MKSG-MugunthKumar** [comment]
This one looks solid!
I'm thinking of adding support for llama3.3 only for their deterministic responses so we can have a cleaner prompt. If you got some time, feel free to give it a go!

**Comment by hummerpj** [comment]
Thanks for the merge. Happy to help. Were you thinking of connecting to a AWS Bedrock instance of Llama 3.3 70B?

I just looked at the pricing and it definitely seems like an interesting alternative to claude for this use case.

**Comment by MKSG-MugunthKumar** [comment]
Not to AWS. but to localhost, ollama managed instance.

**Comment by hummerpj** [comment]
Interesting. From what I've read you'd need a lot of ram to run llama 3.3 70b. Are you on a macbook pro with lots of unified ram?

Its pretty cheap to run in the cloud compared to Claude and GPT api prices.

I'm going to experiment with it running on deepinfra.com since its so cheap there compared to AWS bedrock.  I don't think I'll be able to run on my m2 24gb model directly.

https://artificialanalysis.ai/models/llama-3-3-instruct-70b/providers

**Comment by hummerpj** [comment]
Looks like you can run the "Turbo" version with 8bit quantization on minimum 24gb but also recommends 24 minimum cores, mine has 16 total. Maybe I'll give it a whirl and see how good it performs.

> Prerequisites for Installing Llama-3.3 70B Instruct Locally
> GPU:
> Memory (VRAM):
> Minimum: 24GB (with 8-bit or 4-bit quantization).
> Recommended: 48GB for full precision (FP16 or BF16) for smooth execution.
> Type: NVIDIA GPUs with Tensor Cores (e.g., A100, H100, RTX A6000, RTX 4090).
Multi-GPU Setup (optional for heavy workloads):
2x NVIDIA A100 (80GB) or equivalent for full performance.
Disk Space:
Minimum: 40GB of free SSD space to store model weights and temporary files.
Recommended: At least 1TB SSD for storing checkpoints, logs, and datasets.
RAM:
Minimum: 24GB RAM.
Recommended: 48GB RAM for smoother execution, especially for preprocessing and model loading.
CPU:
Minimum: 24 cores (multi-core processor).
Recommended: 48 cores for optimal performance and faster data preprocessing.

**Pull request merged**
